export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';
export const RECEIVE_USER_ID = 'RECEIVE_USER_ID';
export const RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS';
export const RESET_AUTH = 'RESET_AUTH';
