export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';
export const RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS';
export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS';
export const RECEIVE_USER_ID = 'RECEIVE_USER_ID';
export const RESET_AUTH = 'RESET_AUTH';
export const SET_ACTIVE_ACCOUNT = 'SET_ACTIVE_ACCOUNT';
